export const SHOW_LOADER = "APP/SHOW_LOADER"
export const HIDE_LOADER = "APP/HIDE_LOADER"

export const SHOW_MESSAGE = "APP/SHOW_MESSAGE"
export const HIDE_MESSAGE = "APP/HIDE_MESSAGE"

export const SWITCH_SEARCH_TYPE = 'SEARCH/SWITCH_SEARCH_TYPE'


export const SEARCH_BY_ADDRESS = "SEARCH/SEARCH_BY_ADDRESS"

export const FETCH_REGION = "SEARCH/SEARCH_BY_ADDRESS/FETCH_REGION"
export const SET_REGION = "SEARCH/SEARCH_BY_ADDRESS/SET_REGION"

export const FETCH_AREA = "SEARCH/SEARCH_BY_ADDRESS/FETCH_AREA"
export const SET_AREA = "SEARCH/SEARCH_BY_ADDRESS/SET_AREA"

export const FETCH_SETTLEMENT = "SEARCH/SEARCH_BY_ADDRESS/FETCH_REGION"
export const SET_SETTLEMENT = "SEARCH/SEARCH_BY_ADDRESS/SET_SETTLEMENT"

export const SET_ADDRESS = "SEARCH/SEARCH_BY_ADDRESS/SET_ADDRESS"



export const SEARCH_BY_NAME = "SEARCH/SEARCH_BY_NAME"
export const SEARCH_BY_NOTARY = "SEARCH/SEARCH_BY_NOTARY"
export const SEARCH_USERS = "SEARCH/SEARCH_USERS"

export const CHANGE_NOTARY_TYPE = "SEARCH/CHANGE_NOTARY_TYPE"

export const SEARCH_PRIVATE_NOTATY = "SEARCH/SEARCH_PRIVATE_NOTATY"
export const SEARCH_STATE_NOTARY_DEPARTMENT = "SEARCH/SEARCH_STATE_NOTARY_DEPARTMENT"

export const SEARCH_ADMINISTRATOR = "SEARCH/SEARCH_ADMINISTRATOR"
export const SEARCH_REGISTRATOR = "SEARCH/SEARCH_ADMINISTRATOR"

export const FETCH_ALL_ORGANIZATIONS = "SEARCH/FETCH_ALL_ORGANIZATIONS"
export const SET_ALL_ORGANIZATIONS = "SEARCH/SET_ALL_ORGANIZATIONS"

export const UPDATE_SEARCH_DATA = "SEARCH/UPDATE_SEARCH_DATA"
export const FETCH_SEARCH_DATA = "SEARCH/FETCH_SEARCH_DATA"
export const SET_SEARCH_QUERY_DATA = "SEARCH/SET_SEARCH_QUERY_DATA"

export const CLEAR_SEARCH_DATA = "SEARCH/CLEAR_SEARCH_DATA"


export const SEARCH_NOTARY_BY_ID = "SEARCH/SEARCH_NOTARY_BY_ID"
export const SET_NOTARY_BY_ID = "SEARCH/SET_NOTARY_BY_ID"

export const SEARCH_NOTARY_DEPARTMENT_BY_ID = "SEARCH/SEARCH_NOTARY_DEPARTMENT_BY_ID"
export const SET_NOTARY_DEPARTMENT_BY_ID = "SEARCH/SET_NOTARY_DEPARTMENT_BY_ID"


export const CHANGE_USER_TYPE = "APP/CHANGE_USER_TYPE"

export const ADMINISTRATOR = "APP/ADMINISTRATOR"
export const REGISTRATOR = "APP/REGISTRATOR"
export const COMMON = "APP/COMMON"

export const CREATE_NEW_MESSAGE = "MESSAGE/CREATE_NEW_MESSAGE"
export const UPDATE_MESSAGE_LIST = "MESSAGE/UPDATE_MESSAGE_LIST"
export const SET_MESSAGE_LIST = "MESSAGE/SET_MESSAGE_LIST"
export const MESSAGE_TYPE_GOVERNMENT_NOTARY = 'MESSAGE/MESSAGE_TYPE_GOVERNMENT_NOTARY';
export const MESSAGE_TYPE_PRIVATE_NOTARY = 'MESSAGE/MESSAGE_TYPE_PRIVATE_NOTARY';
export const MESSAGE_TYPE_ORGANIZATION = 'MESSAGE/MESSAGE_TYPE_ORGANIZATION';


export const ADD_NEW_NOTARY = "NOTARIES/ADD_NEW_NOTARY"
export const ADD_NEW_DEPARTMENT = "NOTARIES/ADD_NEW_DEPARTMENT"
export const UPDATE_NOTARY = "NOTARIES/UPDATE_NOTARY"
export const UPDATE_DEPARTMENT = "NOTARIES/UPDATE_DEPARTMENT"
export const DELETE_NOTARY = "NOTARIES/DELETE_NOTARY"
export const DELETE_DEPARTMENT = "NOTARIES/DELETE_DEPARTMENT"


export const ADD_USER = "USERS/ADD_USER"
export const REMOVE_USER = "USERS/REMOVE_USER"


export const LOGIN_USER = "APP/LOGIN_USER"
export const LOGOUT_USER = "APP/LOGOUT_USER"
export const SET_USER_DATA = "APP/SET_USER_DATA"


